build: configure local Docker-based setup for prod

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,33 +1,53 @@
-# Base stage for both development and production
-FROM node:20 as base
+# Development stage
+FROM node:20 AS development
+
+WORKDIR /app
+COPY backend/package.json ./
+RUN npm install
+
+COPY backend/ ./
+
+# Rebuild bcrypt
+RUN npm rebuild bcrypt --build-from-source
+
+# Start in development mode with hot reloading
+CMD node /app/src/migrations/initPostgres.js && npm run dev
+
+# Frontend build stage (for production)
+FROM node:20 AS frontend-builder
+
+WORKDIR /frontend
+COPY frontend/package.json ./
+RUN npm install
+
+COPY frontend/ ./
+RUN npm run build
+
+# Backend build stage (for production)
+FROM node:20 AS backend-builder
+
+WORKDIR /app
+COPY backend/package.json ./
+RUN npm install
+
+COPY backend/ ./
+RUN npm run build || echo "Backend built with TS errors. Continuing."
+
+# Rebuild bcrypt
+RUN npm rebuild bcrypt --build-from-source
+
+# Production stage
+FROM node:20 AS production
 
 WORKDIR /app
 
-# Copy package.json and package-lock.json
-COPY package*.json ./
+# Copy built backend files
+COPY --from=backend-builder /app/dist ./dist
+COPY --from=backend-builder /app/package*.json ./
+RUN npm ci --only=production
 
-# Development stage
-FROM base as development
+# Copy built frontend static files
+COPY --from=frontend-builder /frontend/dist /app/public
 
-# Install all dependencies (including devDependencies)
-RUN npm install
-
-# Copy the rest of the code
-COPY . .
-
-EXPOSE 5001
-
-CMD ["npm", "run", "dev"]
-
-# Production stage (if needed in the future)
-# FROM base as production
-
-# Install only production dependencies
-# RUN npm ci --only=production
-
-# Copy the rest of the code
-# COPY . .
-
-# EXPOSE 5001
-
-# CMD ["npm", "start"]
+# Start production server using compiled javascript
+CMD node /app/dist/migrations/initPostgres.js && npm start
